### ISSUE TITLE
Fix Appveyor

### ISSUE THREAD

**Issue by jbboehr** [pmjones/ext-request#9]

**Comment by sergeyklay** [comment]
Hi @jbboehr, @pmjones 

I've managed to build, release and publish artifacts (DLLs) for PHP 7.0 and 7.1 (x86 and x64 platforms). So I spent a lot of time to figure it out. It wasn't easy, certainly because I have no Windows machine :) 

I'm not sure that you need to have exactly 7.2 for AppVeyor. But anyway it is not hard to add support for this as well as.
 
<img width="1044" alt="AppVeyor builds" src="https://user-images.githubusercontent.com/1256298/34084021-58c4e45e-e382-11e7-9bb2-333ac70f1322.png">


You are free to borrow [any part of my config](https://github.com/sergeyklay/psr/blob/master/.appveyor.yml).

Best regards,

**Comment by jbboehr** [comment]
Thanks! I know what the issue is - I set it up before 7.2 was released and they changed the URLs for the windows php sdk. I'll check out your config.

Incidentally, I see you've made a PSR extension, any reason you didn't use mine?
* https://pecl.php.net/package/psr
* https://github.com/jbboehr/php-psr

**Comment by sergeyklay** [comment]
@jbboehr Wow! I did not know about it!
